spring.application.name=authorization-server
#
spring.threads.virtual.enabled=true
#

#
# tag::client[]
# <.>
spring.security.oauth2.authorizationserver.client.javafx.registration.client-id=javafx
spring.security.oauth2.authorizationserver.client.javafx.registration.client-name=Bootiful JavaFX
spring.security.oauth2.authorizationserver.client.javafx.registration.client-authentication-methods[0]=none
spring.security.oauth2.authorizationserver.client.javafx.registration.authorization-grant-types[0]=authorization_code
spring.security.oauth2.authorizationserver.client.javafx.registration.authorization-grant-types[1]=refresh_token
spring.security.oauth2.authorizationserver.client.javafx.registration.redirect-uris[0]=http://127.0.0.1:8385/login/oauth2/code/javafx
spring.security.oauth2.authorizationserver.client.javafx.registration.scopes[0]=openid
spring.security.oauth2.authorizationserver.client.javafx.registration.scopes[1]=profile
spring.security.oauth2.authorizationserver.client.javafx.registration.scopes[2]=email
spring.security.oauth2.authorizationserver.client.javafx.require-proof-key=true
# end::client[]
#
server.port=9090
#
# tag::datasource[]
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
# end::datasource[]
#
