spring.application.name=bootiful-javafx
server.address=127.0.0.1
server.port=8385
spring.security.oauth2.client.registration.javafx.provider=spring
spring.security.oauth2.client.registration.javafx.client-id=javafx
spring.security.oauth2.client.registration.javafx.client-authentication-method=none
spring.security.oauth2.client.registration.javafx.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.javafx.redirect-uri=http://127.0.0.1:${server.port}/login/oauth2/code/javafx
spring.security.oauth2.client.registration.javafx.scope[0]=openid
spring.security.oauth2.client.registration.javafx.scope[1]=profile
spring.security.oauth2.client.registration.javafx.scope[2]=email
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:9090
#
bootiful.api-uri=http://localhost:9090/userinfo
#
spring.threads.virtual.enabled=true
